name: "darwin-configuration"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: darwin-configuration
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: sh ./cache.sh
